apiVersion: v1
kind: Service
metadata:
  name: metrics
  labels:
    app: metrics
    metrics-discovery: 'true'
spec:
  type: NodePort
  selector:
    app: metrics
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
      name: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
  namespace: default
  labels:
    app: metrics
spec:
  replicas: 5
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
        - name: metrics
          image: ccr.ccs.tencentyun.com/ccr_dev/metrics:latest
          args:
            - -label=4
            - -metrics=1
            - -value=10
            - -value-len=20
            - -label-len=20
          command:
            - /metrics
          ports:
            - containerPort: 9091
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    arms.prometheus.io/discovery: 'true'
  name: monitor-example-app
  namespace: default
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: metrics
